export const INITIAL_TASKS: Task[] = [
  // MONDAY
  {
    id: '1',
    title: 'Client Strategy Call',
    description: 'Discuss Q3 roadmap with stakeholders.',
    focus: 'High',
    duration: 60,
    day: 'Monday',
    isEssential: true,
  },
  {
    id: '2',
    title: 'Email Triage',
    description: 'Clear inbox and flag urgent requests.',
    focus: 'Low',
    duration: 30,
    day: 'Monday',
    isEssential: false,
  },
  {
    id: '3',
    title: 'Team Standup',
    description: 'Daily sync with team.',
    focus: 'Medium',
    duration: 20,
    day: 'Monday',
    isEssential: true,
  },
  {
    id: '4',
    title: 'Resolve P1 Incident',
    description: 'Handle critical system outage.',
    focus: 'High',
    duration: 90,
    day: 'Monday',
    isEssential: true,
  },

  // TUESDAY
  {
    id: '5',
    title: 'Data Analysis Report',
    description: 'Analyze operational metrics.',
    focus: 'High',
    duration: 120,
    day: 'Tuesday',
    isEssential: true,
  },
  {
    id: '6',
    title: 'Ticket Logging',
    description: 'Log incoming service requests.',
    focus: 'Low',
    duration: 45,
    day: 'Tuesday',
    isEssential: false,
  },
  {
    id: '7',
    title: 'Vendor Follow-up',
    description: 'Check updates from vendors.',
    focus: 'Medium',
    duration: 30,
    day: 'Tuesday',
    isEssential: false,
  },
  {
    id: '8',
    title: 'System Debugging',
    description: 'Investigate recurring issue.',
    focus: 'High',
    duration: 90,
    day: 'Tuesday',
    isEssential: true,
  },

  // WEDNESDAY
  {
    id: '9',
    title: 'Documentation Update',
    description: 'Update internal wiki.',
    focus: 'Low',
    duration: 45,
    day: 'Wednesday',
    isEssential: false,
  },
  {
    id: '10',
    title: 'Security Review',
    description: 'Review system vulnerabilities.',
    focus: 'High',
    duration: 60,
    day: 'Wednesday',
    isEssential: true,
  },
  {
    id: '11',
    title: 'Internal Meeting',
    description: 'Discuss ongoing projects.',
    focus: 'Medium',
    duration: 45,
    day: 'Wednesday',
    isEssential: true,
  },
  {
    id: '12',
    title: 'File Organization',
    description: 'Clean up folders and files.',
    focus: 'Low',
    duration: 30,
    day: 'Wednesday',
    isEssential: false,
  },

  // THURSDAY
  {
    id: '13',
    title: 'Bug Scrub',
    description: 'Review and prioritize bugs.',
    focus: 'Medium',
    duration: 60,
    day: 'Thursday',
    isEssential: false,
  },
  {
    id: '14',
    title: 'Critical Ticket Resolution',
    description: 'Fix high-priority tickets.',
    focus: 'High',
    duration: 90,
    day: 'Thursday',
    isEssential: true,
  },
  {
    id: '15',
    title: 'Email Responses',
    description: 'Reply to pending emails.',
    focus: 'Low',
    duration: 40,
    day: 'Thursday',
    isEssential: false,
  },
  {
    id: '16',
    title: 'Performance Monitoring',
    description: 'Check system performance.',
    focus: 'Medium',
    duration: 45,
    day: 'Thursday',
    isEssential: true,
  },

  // FRIDAY
  {
    id: '17',
    title: 'Project Planning',
    description: 'Plan next sprint tasks.',
    focus: 'High',
    duration: 90,
    day: 'Friday',
    isEssential: true,
  },
  {
    id: '18',
    title: 'Weekly Report',
    description: 'Prepare and submit report.',
    focus: 'Medium',
    duration: 60,
    day: 'Friday',
    isEssential: true,
  },
  {
    id: '19',
    title: 'Status Updates',
    description: 'Update task progress.',
    focus: 'Low',
    duration: 30,
    day: 'Friday',
    isEssential: false,
  },
  {
    id: '20',
    title: 'System Cleanup',
    description: 'Archive old data and logs.',
    focus: 'Low',
    duration: 45,
    day: 'Friday',
    isEssential: false,
  },
];